include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_print
    - avoid_empty_else
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - sort_child_properties_last

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
